from __future__ import annotations

# Static aliases supported by run_tool_by_name and command suggestions.
# Dynamic aliases from ofti.tools/ofti.postprocessing are added at runtime.
STATIC_TOOL_ALIAS_GROUPS: tuple[tuple[str, ...], ...] = (
    ("rerun", "last"),
    ("highspeed", "high_speed", "highspeedhelper"),
    ("boundarymatrix", "boundary-matrix"),
    ("initialconditions", "initial-conditions"),
    ("thermowizard", "thermo-wizard"),
    ("blockmeshhelper", "blockmesh-helper"),
    ("snappystaged", "snappy-staged"),
    ("pipelineedit", "pipeline-edit"),
    ("pipelinerun", "pipeline-run"),
    ("parametricwizard", "parametric-wizard"),
    ("fieldsummary", "field-summary"),
    ("postprocessingbrowser", "postprocessing-browser"),
    ("samplingsets", "sampling-sets", "sampling"),
    ("runparallel", "run-parallel"),
    ("meshquality", "mesh-quality", "checkmesh"),
    ("physicshelpers", "physics-helpers"),
    ("runscript",),
    ("postprocess",),
    ("foamcalc",),
    ("runcurrentsolver",),
    ("runlive",),
    ("removelogs",),
    ("cleantimedirs",),
    ("reconstruct_manager", "reconstructmanager"),
    ("timedir_pruner", "timedirpruner"),
    ("safestop",),
    ("solveresume",),
    ("clone",),
    ("yplus",),
    ("logs", "viewlogs"),
    ("residuals", "residual_timeline"),
    ("probes", "probesviewer"),
    ("loganalysis",),
    ("paraview",),
    ("diagnostics",),
    ("casedoctor",),
    ("jobstatus",),
    ("jobstart",),
    ("jobstop",),
    ("jobpause",),
    ("jobresume",),
    ("clitools", "cli-tools"),
    ("knife",),
    ("plot",),
    ("watch",),
    ("run",),
    ("renumbermesh",),
    ("transformpoints",),
    ("cfmesh",),
)

STATIC_TOOL_ALIAS_NAMES: tuple[str, ...] = tuple(
    name for group in STATIC_TOOL_ALIAS_GROUPS for name in group
)
